server:
  port: 9147
  servlet:
    context-path: /super/world

rdb:
  type: dm
# 数据库配置
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://10.1.56.232:3306/super_world?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: dbuser
#    password: DBuser@123_!@#
#    driver-class-name: dm.jdbc.driver.DmDriver
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:dm://DM_SERVER/super_world?DM_SERVER=(10.249.1.5:5236,10.249.7.33:5236)&comOracle=true&databaseProductName=Oracle&compatibleMode=oracle&loginMode=1&localTimezone=480&switchTimes=2000&switchInterval=10
#    username: super_world
#    password: Dmdm2021#)*^
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      max-wait: 10000
      time-between-eviction-runs-millis: 600000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: dm.jdbc.driver.DmDriver
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:dm://DM_SERVER/super_world?DM_SERVER=(10.249.1.5:5236,10.249.7.33:5236)&comOracle=true&databaseProductName=Oracle&compatibleMode=oracle&loginMode=1&localTimezone=480&switchTimes=2000&switchInterval=10
          username: super_world
          password: Dmdm2021#)*^
        component_manager:
          driver-class-name: dm.jdbc.driver.DmDriver
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:dm://DM_SERVER/component_manager?DM_SERVER=(10.249.1.5:5236,10.249.7.33:5236)&comOracle=true&databaseProductName=Oracle&compatibleMode=oracle&loginMode=1&localTimezone=480&switchTimes=2000&switchInterval=10
          username: component_manager
          password: Dmdm2021#)*^
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  flyway:
    enabled: true
    table: flyway_schema_history
    locations: classpath:db/migration/${rdb.type:mysql}
  redis:
    host: 10.1.56.244
    port: 6379
    password: Redis@456_$%^

# Apollo配置
app:
  id: super_world
apollo:
  meta: http://10.1.50.55:7546
  bootstrap:
    enabled: true
    namespaces: application

# MyBatis配置
mybatis:
  mapper-locations: classpath*:mappers/common/*Mapper.xml,classpath*:mappers/${rdb.type:mysql}/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# Knife4j、Swagger配置
knife4j:
  # 开启增强
  enable: true
  # 开启登录认证
  basic:
    enable: true
    username: admin
    password: admin798

# ES配置
elasticsearch:
  http:
    hosts: 10.249.1.93:9200
    username: admin
    password: uyun.Elasticsearch_2024@Broada
  cluster:
    name: elasticsearch
dubbo:
  application:
    name: super_world
  registry:
    address: zookeeper://10.249.5.121:2181
